apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-10-03T16:33:08Z"
  generation: 1
  labels:
    app: pokedex
  name: pokedex
  namespace: default
  resourceVersion: "87281"
  uid: 351c64fd-5447-4a52-a19a-e9ed6fe4da37
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pokedex
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pokedex
    spec:
      containers:
      - image: yashdaga81/pokedex-pokemon
        imagePullPolicy: Always
        name: pokedex-pokemon
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-10-03T16:33:13Z"
    lastUpdateTime: "2023-10-03T16:33:13Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-10-03T16:33:08Z"
    lastUpdateTime: "2023-10-03T16:33:13Z"
    message: ReplicaSet "pokedex-78558b565f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
