apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-10-03T16:40:39Z"
  labels:
    app: pokedex
  name: pokedex-service
  namespace: default
  resourceVersion: "87654"
  uid: ce176038-148e-40b1-b355-36ae794ee2a2
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.101.71.112
  clusterIPs:
  - 10.101.71.112
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31499
    port: 3030
    protocol: TCP
    targetPort: 3000
  selector:
    app: pokedex
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
